version: '3.4'

services:
  linkcutter.api:
    image: ${DOCKER_REGISTRY-}linkcutter
    build:
      context: .
      dockerfile: LinkCutter.Api/Dockerfile
    ports:
      - "7106:7106"
    environment:
      - ASPNETCORE_URLS=http://*:7106
    depends_on: 
        - mssql
    networks:
      - app-network
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sql2
    hostname: mssql
    environment:
      - SA_PASSWORD=P@ssword1
      - ACCEPT_EULA=Y
    restart: unless-stopped
    ports:
      - "1401:1433" 
    networks:
      - app-network
networks:
  app-network:
    driver: bridge